<?php

/**
 * @file
 * Primary module hooks for Neo | Color module.
 */

use Drupal\neo_color\PalletInterface;
use Drupal\neo_color\SchemeInterface;

/**
 * Implements hook_theme().
 */
function neo_color_theme(): array {
  return [
    'neo_pallet_preview' => [
      'variables' => ['neo_pallet' => NULL],
    ],
    'neo_pallet_swatches' => [
      'variables' => ['neo_pallet' => NULL],
    ],
    'neo_scheme_preview' => [
      'variables' => ['neo_scheme' => NULL],
    ],
    'neo_scheme_swatch' => [
      'variables' => ['neo_scheme' => NULL],
    ],
  ];
}

/**
 * Loads a Neo color pallet by its ID.
 *
 * @param string $pallet_id
 *   The ID of the pallet to load.
 *
 * @return \Drupal\neo_color\PalletInterface|null
 *   Returns the pallet object if found, or NULL if not found.
 */
function neo_color_get_pallet($pallet_id): ?PalletInterface {
  $scheme = \Drupal::entityTypeManager()->getStorage('neo_pallet')->load($pallet_id);
  if ($scheme instanceof PalletInterface) {
    return $scheme;
  }
  return NULL;
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_neo_pallet_preview(&$variables) {
  $pallet = $variables['neo_pallet'];
  if ($pallet instanceof PalletInterface) {
    $shade = $pallet->getShade(500);
    $variables['hex'] = $shade->getHex();
    $variables['content_hex'] = $shade->getContentHex();
    $variables['rgb'] = implode(', ', $shade->getRgb());
    $hsl = $shade->getHsl();
    $variables['hsl'] = 'hsl(' . $hsl['h'] . ', ' . $hsl['s'] . '%, ' . $hsl['l'] . '%)';
    $variables['shades'] = $pallet->getShades();
  }
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_neo_pallet_swatches(&$variables) {
  $pallet = $variables['neo_pallet'];
  if ($pallet instanceof PalletInterface) {
    $variables['shades'] = $pallet->getShades();
  }
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_neo_scheme_preview(&$variables) {
  /** @var \Drupal\neo_color\SchemeInterface $scheme */
  $scheme = $variables['neo_scheme'];
  if ($scheme instanceof SchemeInterface) {
    $variables['label'] = $scheme->label();
    $variables['dark'] = $scheme->get('dark');
    $variables['colorize'] = $scheme->get('colorize');
    $variables['colorize_offset'] = (int) ($scheme->get('colorize_offset') ?? 100);
    $variables['selector'] = $scheme->getSelector();
    $variables['base'] = $scheme->getBase();
    $variables['primary'] = $scheme->getPrimary();
    $variables['secondary'] = $scheme->getSecondary();
    $variables['accent'] = $scheme->getAccent();
    $variables['css'] = [
      '#type' => 'html_tag',
      '#tag' => 'style',
      '#value' => $scheme->getCss(),
      '#attributes' => [
        'neo-scheme' => '',
      ],
    ];
  }
}

/**
 * Implements template_preprocess().
 */
function template_preprocess_neo_scheme_swatch(&$variables) {
  /** @var \Drupal\neo_color\SchemeInterface $scheme */
  $scheme = $variables['neo_scheme'];
  if ($scheme instanceof SchemeInterface) {
    $variables['label'] = $scheme->label();
    $variables['dark'] = $scheme->get('dark');
    $variables['colorize'] = $scheme->get('colorize');
    $variables['selector'] = $scheme->getSelector();
    $variables['base'] = $scheme->getBase();
    $variables['primary'] = $scheme->getPrimary();
    $variables['secondary'] = $scheme->getSecondary();
    $variables['accent'] = $scheme->getAccent();
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function neo_color_field_formatter_info_alter(&$info) {
  $info['entity_reference_entity_id']['field_types'][] = 'neo_scheme';
  $info['entity_reference_entity_view']['field_types'][] = 'neo_scheme';
  $info['entity_reference_label']['field_types'][] = 'neo_scheme';
  $info['neo_entity_attribute']['field_types'][] = 'neo_scheme';
}
